### ISSUE TITLE
[FE] 모바일 페이지, IOS 최적화 및 수정

### ISSUE THREAD

**Issue by cks3066** [woowacourse-teams/2022-gong-check#558]
## as-is
- [x]  아이폰8 에서는 빠르게 스크롤을 올렸을떄 헤더 위의 영역이 생김 #579
- [x]  안드로이드에서는 링크 복사가 되는 반면, IOS 에서는 링크 복사가 실행되지 않음 #566
- [x]  아이폰8 에서는 슬라이더 메뉴 애니메이션이 끊겨서 보임 #579
- [x] 랜딩페이지 실제 핸드폰으로 볼 때 끊겨보이는 현상 존재
- [x] 랜딩 페이지 버튼이 왔다갔다 거림
